project:
  type: website
  output-dir: docs

website:
  title: "Gabrielle Hoover"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mp1.qmd
      - maps.qmd
  page-footer: 
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}
    left: Find the source code to this website on my [GitHub](https://github.com/ghoover24/ghoover24.github.io){target=_blank}


format:
  html:
    theme:
      - styles.css
    css: styles.css
    toc: true



