---
title: "About"
---
# More about me!

## Clarinet 

I started playing the clarinet in fifth grade mostly to be different than my brothers who chose to play brass instruments. I kept playing throughout middle and high school and it eventually brought me here to St. Olaf! Now, I play in both the St. Olaf Band and St. Olaf Orchestra. I also serve as the ensemble librarian for the band!

During my Spring advising meeting this year, my advisor asked me why I am so involved in music despite not being a major. That question really gave me some pause and sparked a lot of reflection. My first answer was "what else would I do?" I don't see my life without clarinet as it has brought me many friends and experiences. Touring with the Orchestra and Band around the country has been amazing (the picture above is from the most recent Orchestra tour in Montana!)! Even when the locations can seem a little mundane (Northern Minnesota in January...), bandies and orchies always find ways to have a great time! How could I miss out on that! 

While there are many answers to my advisor's question, I always come back to the community and "out" music at St. Olaf provides. To me, it feels like the Penny Lane quote from the movie Almost Famous "If you ever get lonely, just go to the record store and visit your friends" except the record store is Christiansen Hall of Music :) 

## Currently Watching

Right now, I am watching season 2 of The Pitt with one of my friends. 10 out of 10 show, it's insane. I've also been watching The Sopranos as my older brother highly recommended it (despite only watching the first few episodes). Paulie "Walnuts" Gualtieri is my favorite character but Carmela Soprano is a close second! 

I've also been following Survivor 50 this season (really rooting for Cirie!!). While I have many opinions on this season, nobody needs to hear them :) (get Coach off of my screen please)


